CREATE DATABASE STEALAR;

USE STEALAR

CREATE TABLE CLIENTE(
IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME CHAR(30) UNIQUE,
APELIDO VARCHAR(20),
EMAIL VARCHAR(30) NOT NULL,
CPF BIGINT(11) UNIQUE, 
DATA_DE_NASCIMENTO DATETIME NOT NULL, 
DDD INT(2),
NUMERO INT(9)
);

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    LOGRADOURO VARCHAR(50) NOT NULL,
    NUMERO INT(6),
    BAIRRO VARCHAR(15) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    UF CHAR(4) NOT NULL,
    CEP INT(8),
    COMPLEMENTO CHAR(30),
    ID_CLIENTE INT,

FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE FORMA_DE_PAGAMENTO(
    IDFORMADEPAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME ENUM('PIX', 'CARTÃO DE CRÉDITO', 'CARTÃO DE DÉBITO')
);

CREATE TABLE DADOS_DO_CARTÃO(
    BANDEIRA ENUM('MASTERCARD','VISA','ELO','AMERICAN EXPRESS','CAIXA'),
    CVV INT,
    TITULAR CHAR(20),
    VALIDADE DATE,
    CONTA_BANCARIA INT(14),
    ID_CLIENTE INT NOT NULL,

FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL, 
    CATEGORIA VARCHAR(100) NOT NULL,
    TAMANHOS_DISPONIVEIS ENUM('PP','P','M','G','GG','GGG')
);

CREATE TABLE FUNCIONARIOS(
    IDFUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    SALARIO FLOAT(5,3) NOT NULL
);

INSERT INTO CLIENTE VALUES(1,'VITOR HUGO','HUGUINHO','O.HUGO.FAMOSQUEBRACU@GMAIL.COM',09453276805,29/01/1988,NULL,NULL);
INSERT INTO ENDERECO VALUES(1,'RUA',6,'BAIRRO','CIDADE','UF','85240664',NULL,1);
INSERT INTO DADOS_DO_CARTÃO VALUES(1,'VITOR HUGO',15/05/2024,'ELO',951,1);
INSERT INTO PRODUTO VALUES(35,'CAMISA MANGA LONGA','CAMISA','M');
INSERT INTO FUNCIONARIOS VALUES(11,'HENRIQUE',2.389);
