CREATE DATABASE CONTROLE_DE_ESTOQUE

USE CONTROLE_DE_ESTOQUE

CREATE TABLE CLIENTE(
    IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME CHAR(30) NOT NULL,
    CPF INT(11) NOT NULL,
    CEP INT(8) NOT NULL,
    ENDERECO VARCHAR(50) NOT NULL,
    BAIRRO CHAR(30) NOT NULL,
    CIDADE CHAR(50) NOT NULL,
    ESTADO CHAR(50) NOT NULL,
    DDD INT(11) NOT NULL,
    NUMERO INT(9) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,


FOREIGN KEY (ID_COMPRA)
REFERENCES COMPRAS(IDCOMPRA)
);

CREATE TABLE COMPRA(
    IDCOMPRA INT PRIMARY KEY AUTO_INCREMENT,
    DATA_COMPRA DATE NOT NULL,
    NOTA_FISCAL INT NOT NULL,
    TOTAL MONEY NOT NULL,
    FORMA_PAGAMENTO ENUM('PIX', 'CARTÃO CRÉDITO', 'CARTÃO DÉBITO'),
    QUANTIDADE_PARCELAS INT,
    STATUS_COMPRA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    ID_FORNECEDOR INT NOT NULL,

SELECT P.NOME, 
       P.VALOR_VENDA, 
       V.DATA_VENDA, 
       Q.ITENS_COMPRA
FROM PRODUTO P 
INNER JOIN VENDA V 
ON P.IDPRODUTO = V.ID_PRODUTO 
INNER JOIN ITENS_COMPRA I 
ON P.IDPRODUTO = I.ID_PRODUTO
);

CREATE TABLE PARCELAS_COMPRA(
    IDPARCELASCOMPRA INT NOT NULL,
    VALOR MONEY NOT NULL,
    QUANTIDADE_PARCELAS INT(2) NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,

SELECT DATA_COMPRA.C,
       TOTAL.C,
       FORMA_PAGAMENTO.C
FROM VENDA V
INNER JOIN COMPRA C 
);

CREATE TABLE FORNECEDOR(
    IDFORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME CHAR(50) NOT NULL,
    CNPJ INT(11) NOT NULL,
    CEP INT(8) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    BAIRRO CHAR(30) NOT NULL,
    CIDADE CHAR(50) NOT NULL,
    ESTADO CHAR(50) NOT NULL,
    DDD INT(2) NOT NULL,
    NUMERO INT(9) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ID_PRODUTO INT NOT NULL,

FOREIGN KEY(ID_PRODUTO)
REFERENCES PRODUTO(IDPRODUTO)
);

CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    FOTO IMAGE NOT NULL,
    VALOR_PAGO MONEY NOT NULL,
    VALOR_VENDA MONEY NOT NULL,
    QUANTIDADE_DISPONIVEL FLOAT(3,2) NOT NULL,


FOREIGN KEY (ID_FORNECEDOR)
REFERENCES FORNECEDOR(IDFORNECEDOR)
);

CREATE TABLE ITENS_COMPRA(
    IDITENSCOMPRA INT PRIMARY KEY AUTO_INCREMENT,
    PRODUTO CHAR(50) NOT NULL
    QUANTIDADE FLOAT NOT NULL,
    VALOR MONEY NOT NULL,
    ID_PRODUTO INT NOT NULL,

SELECT NOME.P,
       VALOR_VENDA.P,
       TOTAL.V,
       STATUS_VENDA.V
FROM VENDA V
INNER JOIN PRODUTO P
ON V.IDVENDA = P.ID_VENDA
INNER JOIN COMPRA C
ON V.IDVENDA = C.ID_VENDA  
);

CREATE TABLE VENDA(
    IDVENDA INT PRIMARY KEY AUTO_INCREMENT,
    DATA_VENDA DATE NOT NULL,
    NOTA_FISCAL INT NOT NULL,
    TOTAL MONEY NOT NULL,-
    NUMERO_PARCELAS INT NOT NULL,
    STATUS_VENDA INT NOT NULL,
    FORMA_PAGAMENTO ENUM('PIX', 'CARTÃO CRÉDITO', 'CARTÃO DÉBITO') NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    
SELECT NOME.P,
       VALOR_VENDA.P,
       QUANTIDADE.I
FROM VENDA V
INNER JOIN FORMADEPAGAMENTO F
ON P.PRODUTO = F.ID_PRODUTO 
INNER JOIN ITENS_COMPRA I  
ON P.IDPRODUTO = I.ID_PRODUTO 
INNER JOIN PARCALAS A
ON  P.IDPRODUTO = A.ID_PRODUTO
);
-
